### ISSUE TITLE
Add Windows Support

### ISSUE THREAD

**Issue by peterzhuamazon** [opensearch-project/geospatial#158]
Coming from https://github.com/opensearch-project/opensearch-plugins/issues/95, add Windows support.

- [x] Passing CI on Windows
- [x] Documentation

**Comment by heemin32** [comment]
Build on Window for main branch does not work with following error. The issue could be related with OpenSearch 3.0.0-SNAPSHOT as a build with OpenSearch 2.4.0-SNAPSHOT works.
```
�    ? errors and warnings from D:\a\geospatial\geospatial\build\testclusters\integTest-0\logs\opensearch.stdout.log ?
=== Standard error of node `node{::integTest-0}` ===
� ERROR][o.o.b.OpenSearchUncaughtExceptionHandler] [integTest-0] uncaught exception in thread [main]
�  org.opensearch.bootstrap.StartupException: java.lang.RuntimeException: can not run opensearch as root
�  	at org.opensearch.bootstrap.OpenSearch.init(OpenSearch.java:184) ~[opensearch-3.0.0-SNAPSHOT.jar:3.0.0-SNAPSHOT]
�  	at org.opensearch.bootstrap.OpenSearch.execute(OpenSearch.java:171) ~[opensearch-3.0.0-SNAPSHOT.jar:3.0.0-SNAPSHOT]
�  	at org.opensearch.cli.EnvironmentAwareCommand.execute(EnvironmentAwareCommand.java:104) ~[opensearch-3.0.0-SNAPSHOT.jar:3.0.0-SNAPSHOT]
�  	at org.opensearch.cli.Command.mainWithoutErrorHandling(Command.java:138) ~[opensearch-cli-3.0.0-SNAPSHOT.jar:3.0.0-SNAPSHOT]
�  	at org.opensearch.cli.Command.main(Command.java:101) ~[opensearch-cli-3.0.0-SNAPSHOT.jar:3.0.0-SNAPSHOT]
�  	at org.opensearch.bootstrap.OpenSearch.main(OpenSearch.java:137) ~[opensearch-3.0.0-SNAPSHOT.jar:3.0.0-SNAPSHOT]
�  	at org.opensearch.bootstrap.OpenSearch.main(OpenSearch.java:103) ~[opensearch-3.0.0-SNAPSHOT.jar:3.0.0-SNAPSHOT]
�  Caused by: java.lang.RuntimeException: can not run opensearch as root
�  	at org.opensearch.bootstrap.Bootstrap.initializeNatives(Bootstrap.java:124) ~[opensearch-3.0.0-SNAPSHOT.jar:3.0.0-SNAPSHOT]
�  	at org.opensearch.bootstrap.Bootstrap.setup(Bootstrap.java:191) ~[opensearch-3.0.0-SNAPSHOT.jar:3.0.0-SNAPSHOT]
�  	at org.opensearch.bootstrap.Bootstrap.init(Bootstrap.java:[404](https://github.com/heemin32/geospatial/actions/runs/3253777954/jobs/5341360413#step:4:405)) ~[opensearch-3.0.0-SNAPSHOT.jar:3.0.0-SNAPSHOT]
�  	at org.opensearch.bootstrap.OpenSearch.init(OpenSearch.java:180) ~[opensearch-3.0.0-SNAPSHOT.jar:3.0.0-SNAPSHOT]
�  	... 6 more
�   ? last 40 non error or warning messages from D:\a\geospatial\geospatial\build\testclusters\integTest-0\logs\opensearch.stdout.log ?
```
https://github.com/heemin32/geospatial/actions/runs/3253361449/jobs/5340559789#step:4:462

**Comment by dblock** [comment]
Are integration/cypress tests also running? If not please reopen this issue.

**Comment by heemin32** [comment]
integration tests are running in all platforms.
