### ISSUE TITLE
[FlakyTest]class org.opensearch.geospatial.search.aggregations.bucket.geogrid.GeoHexGridTests

### ISSUE THREAD

**Issue by heemin32** [opensearch-project/geospatial#309]
```
Suite: Test class org.opensearch.geospatial.search.aggregations.bucket.geogrid.GeoHexGridTests
  2> REPRODUCE WITH: ./gradlew ':test' --tests "org.opensearch.geospatial.search.aggregations.bucket.geogrid.GeoHexGridTests.testFromXContentWithRandomFields" -Dtests.seed=F8B57BA4BDC3BC8D -Dtests.security.manager=false -Dtests.locale=es-PR -Dtests.timezone=Atlantic/Faeroe -Druntime.java=11
  2> java.lang.AssertionError: expected:<668957070> but was:<537200555>
        at __randomizedtesting.SeedInfo.seed([F8B57BA4BDC3BC8D:FAA056E5E6043458]:0)
        at org.junit.Assert.fail(Assert.java:89)
        at org.junit.Assert.failNotEquals(Assert.java:835)
        at org.junit.Assert.assertEquals(Assert.java:647)
        at org.junit.Assert.assertEquals(Assert.java:633)
        at org.opensearch.test.InternalMultiBucketAggregationTestCase.assertBucket(InternalMultiBucketAggregationTestCase.java:185)
        at org.opensearch.test.InternalMultiBucketAggregationTestCase.assertMultiBucketsAggregations(InternalMultiBucketAggregationTestCase.java:156)
        at org.opensearch.test.InternalMultiBucketAggregationTestCase.assertFromXContent(InternalMultiBucketAggregationTestCase.java:118)
        at org.opensearch.test.InternalAggregationTestCase.testFromXContentWithRandomFields(InternalAggregationTestCase.java:481)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at com.carrotsearch.randomizedtesting.RandomizedRunner.invoke(RandomizedRunner.java:1750)
        at com.carrotsearch.randomizedtesting.RandomizedRunner$8.evaluate(RandomizedRunner.java:938)
        at com.carrotsearch.randomizedtesting.RandomizedRunner$9.evaluate(RandomizedRunner.java:974)
        at com.carrotsearch.randomizedtesting.RandomizedRunner$10.evaluate(RandomizedRunner.java:988)
        at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
        at org.junit.rules.RunRules.evaluate(RunRules.java:20)
        at org.apache.lucene.tests.util.TestRuleSetupTeardownChained$1.evaluate(TestRuleSetupTeardownChained.java:48)
        at org.apache.lucene.tests.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:43)
```

**Comment by VijayanB** [comment]
Added to backlog to prioritize
