### ISSUE TITLE
[BUG][DISTRIBUTION] 2.10.0 Jarhell for installing geospatial plugin to bundle

### ISSUE THREAD

**Issue by peterzhuamazon** [opensearch-project/geospatial#399]
https://build.ci.opensearch.org/blue/organizations/jenkins/distribution-build-opensearch/detail/distribution-build-opensearch/8369/pipeline/75/

```
2023-09-05 16:03:46 INFO     Installing geospatial

2023-09-05 16:03:46 INFO     Executing "/tmp/tmp3dh2uzls/opensearch-2.10.0/bin/opensearch-plugin install --batch file:/tmp/tmp3dh2uzls/opensearch-geospatial-2.10.0.0.zip" in /tmp/tmp3dh2uzls/opensearch-2.10.0

-> Installing file:/tmp/tmp3dh2uzls/opensearch-geospatial-2.10.0.0.zip

-> Downloading file:/tmp/tmp3dh2uzls/opensearch-geospatial-2.10.0.0.zip

-> Failed installing file:/tmp/tmp3dh2uzls/opensearch-geospatial-2.10.0.0.zip

-> Rolling back file:/tmp/tmp3dh2uzls/opensearch-geospatial-2.10.0.0.zip

-> Rolled back file:/tmp/tmp3dh2uzls/opensearch-geospatial-2.10.0.0.zip

Exception in thread "main" java.lang.IllegalStateException: failed to load plugin opensearch-geospatial due to jar hell

	at org.opensearch.plugins.PluginsService.checkBundleJarHell(PluginsService.java:681)

	at org.opensearch.plugins.InstallPluginCommand.jarHellCheck(InstallPluginCommand.java:862)

	at org.opensearch.plugins.InstallPluginCommand.loadPluginInfo(InstallPluginCommand.java:830)

	at org.opensearch.plugins.InstallPluginCommand.installPlugin(InstallPluginCommand.java:875)

	at org.opensearch.plugins.InstallPluginCommand.execute(InstallPluginCommand.java:276)

	at org.opensearch.plugins.InstallPluginCommand.execute(InstallPluginCommand.java:250)

	at org.opensearch.cli.EnvironmentAwareCommand.execute(EnvironmentAwareCommand.java:104)

	at org.opensearch.cli.Command.mainWithoutErrorHandling(Command.java:138)

	at org.opensearch.cli.MultiCommand.execute(MultiCommand.java:104)

	at org.opensearch.cli.Command.mainWithoutErrorHandling(Command.java:138)

	at org.opensearch.cli.Command.main(Command.java:101)

	at org.opensearch.plugins.PluginCli.main(PluginCli.java:60)

Caused by: java.lang.IllegalStateException: jar hell!

class: org.apache.commons.lang3.AnnotationUtils$1

jar1: /tmp/tmp3dh2uzls/opensearch-2.10.0/plugins/.installing-9561255790482694897/commons-lang3-3.12.0.jar

jar2: /tmp/tmp3dh2uzls/opensearch-2.10.0/lib/commons-lang3-3.13.0.jar

	at org.opensearch.bootstrap.JarHell.checkClass(JarHell.java:316)

	at org.opensearch.bootstrap.JarHell.checkJarHell(JarHell.java:215)

	at org.opensearch.plugins.PluginsService.checkBundleJarHell(PluginsService.java:679)

	... 11 more
```

Thanks.

**Comment by heemin32** [comment]
Upgraded commons-lang3-3.12.0 to commons-lang3-3.13.0. https://github.com/opensearch-project/geospatial/commit/2f551547193709a58ec29b092cacb0d2989eea00
